export const reducerTypes = {
    routes: {

    },
    login:{

        LOGIN: 'LOGIN',
        LOGIN_PENDING: 'LOGIN_PENDING',
        LOGIN_SUCCESS: 'LOGIN_SUCCESS',
        LOGIN_ERROR: 'LOGIN_ERROR',

        SET_ACCESSTOKEN: 'SET_ACCESSTOKEN',
        GET_ACCESSTOKEN:'GET_ACCESSTOKEN',
        DELETE_ACCESSTOKEN:'DELETE_ACCESSTOKEN',
        UNAUTHOURIZED: 'UNAUTHOURIZED',

        LOGOUT: 'LOGOUT',
        LOGOUT_PENDING: 'LOGOUT_PENDING',
        LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
        LOGOUT_ERROR: 'LOGOUT_ERROR'
    },
    schoolConstants: {
        GET_SCHOOL_LIST_REQUEST: "GET_SCHOOL_LIST_REQUEST",
        GET_SCHOOL_LIST_SUCCESS: "GET_SCHOOL_LIST_SUCCESS",
        GET_SCHOOL_LIST_FAILURE: "GET_SCHOOL_LIST_FAILURE",
        REGISTER_SCHOOL:'REGISTER_SCHOOL',
        REGISTER_SCHOOL_SUCCESS:'REGISTER_SCHOOL_SUCCESS',
        REGISTER_SCHOOL_FAILURE:'REGISTER_SCHOOL_FAILURE',
        REGISTER_SCHOOL_PENDING:'REGISTER_SCHOOL_PENDING'
    }


}